module.exports = {
  USER_ACCOUNT_CREATED: "User account created.",
  DATABASE_CONNECTED: "Database connected.",
  DATABASE_CONNECTION_ERROR: "Failed to connect to database.",
  INTERNAL_SERVER_ERROR: "Internal server error.",
  USER_LOGGED_IN: "User logged in.",
  INCORRECT_CREDENTIALS: "Incorrect credentials.",
  USER_LOGGED_IN: "User logged in.",
  USER_PROFILE_UPDATED: "User profile updated.",
  USER_PROFILE_FETCHED: "User profile fetched.",
  USER_PROFILE_DELETED: "User account deleted.",
  USER_ALREADY_EXIST: "User already exists.",
  FAILED_TO_REGISTER_AS_USER: "Failed to register a user account.",
  FAILED_TO_UPDATE_PROFILE: "Failed to edit profile.",
  FAILED_TO_DELETE_ACCOUNT: "Failed to delete account.",
  TOKEN_NOT_AUTHORIZED: 'Token not authorized.',
  TOKEN_NOT_VALID: 'Token not valid.',
  CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect.',
  PASSWORD_CHANGED: 'Password changed successfully.',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token.',
  NEW_ACCESS_TOKEN: 'New access token generated.',
};
